name: Update MarkDown

on:
  schedule:
    - cron: '0 2 * * *' # 每天 UTC 时间 2 点运行 (北京时间 10 点)
    
  workflow_dispatch:
    inputs:
      username:
        description: 'username'
        type: string
        default: '123'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许写入内容
    
    steps:
    - uses: actions/checkout@v3 # 检出仓库
    
    - name: Set up JDK # 设置 JDK
      uses: actions/setup-java@v3 # 使用 actions/setup-java@v3 来设置 JDK
      with:
        java-version: '25'
        distribution: 'temurin' # 使用 temurin 分布

    - name: Run java
      run: java -jar IT1024.jar

    - name: Commit and push changes
      run: |
        git config --local user.email "admin@dsttl3.cn"
        git config --local user.name "dsttl3"
        git add markdown
        git diff --quiet && git diff --staged --quiet || git commit -m "Update MarkDown"
        git push